version: "2.1"

services:
    app:
        build: ./app
        network_mode: host
        privileged: true
        restart: always
        labels:
            io.balena.features.dbus: '1'
            io.balena.features.kernel-modules: '1'
            io.balena.features.firmware: '1'
            io.balena.features.supervisor-api: '1'
        cap_add:
            - NET_ADMIN
            - SYS_RAWIO
        environment:
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
        ports:
            - "80:80"
    mqtt:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
